//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWBrasil.ORM.CommandTemplate {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Templates : global::System.Configuration.ApplicationSettingsBase {
        
        private static Templates defaultInstance = ((Templates)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Templates())));
        
        public static Templates Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\nSELECT \n\t{0}\nFROM\n\t{1}\nWHERE\n\t{2}")]
        public string Procedure_Select {
            get {
                return ((string)(this["Procedure_Select"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DELETE FROM {0} WHERE {1}")]
        public string Procedure_Delete {
            get {
                return ((string)(this["Procedure_Delete"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"IF EXISTS ( SELECT 1 FROM sys.objects WHERE type='P' AND name='{0}')
	DROP PROC {0}
GO


CREATE PROC dbo.{0} 
(
	{1}
	,@AbreTransacao		char(1)		= 'N'
	,@CodigoRetorno		int			=  0	output
	,@DescricaoRetorno	varchar(max)= ''	output
) AS
BEGIN

	DECLARE @TransacaoAberta char(1)
		SET @TransacaoAberta = 'N'

	BEGIN TRY

		IF @AbreTransacao = 'S'
		BEGIN
			BEGIN TRAN 
			SET @TransacaoAberta = 'S'
		END


		{2}


		SELECT 	 @CodigoRetorno		= 0
				,@DescricaoRetorno	= ''


		IF @TransacaoAberta = 'S'
		BEGIN
			COMMIT TRAN
			SET @TransacaoAberta = 'N'
		END

	END TRY
	BEGIN CATCH

		SELECT 	 @CodigoRetorno		= -9
				,@DescricaoRetorno	= 'Erro de Processamento'
				

		IF @TransacaoAberta = 'S'
		BEGIN
			ROLLBACK TRAN
			SET @TransacaoAberta = 'N'
		END

	END CATCH

END
GO
")]
        public string Procedure_Base {
            get {
                return ((string)(this["Procedure_Base"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\n--SAVE\nIF EXISTS( SELECT 1 FROM {0} WHERE {1})\nBEGIN\n\n\tUPDATE\n\t\t{0}\n\tSET\n\t\t{2}\n\t" +
            "WHERE\n\t\t{1}\n\nEND\nELSE\nBEGIN\n\n\tINSERT\n\t\tINTO {0}\n\t\t(\n\t\t\t{3}\n\t\t)\n\t\tVALUES\n\t\t(\n\t\t\t{" +
            "4}\n\t\t)\n\n\t{5}\n\nEND")]
        public string Procedure_Save {
            get {
                return ((string)(this["Procedure_Save"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"
[MapperClass(Storable = ""{0}"")]
    public class {0} : DataAccessLibrary
    {
        
        {1}

        #region Persistence Methods

        public new int Save()
        {
            return base.Save();
        }

        public new int Delete()
        {
            return base.Delete();
        }

        #endregion Persistence Methods
		
		#region Search Methods
		
		{2}

		#endregion Search Methods
    }")]
        public string NapierModel {
            get {
                return ((string)(this["NapierModel"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"

<Storable name=""mcs{0}"">
    <Execution cod=""SEL"">
      <Summary>SEL Summary</Summary>
      <Table>{0}</Table>
      <Inputs>
       {1}
      </Inputs>
    </Execution>
    <Execution cod=""INS"">
      <Summary>INS Summary</Summary>
      <Table>{0}</Table>
      <Inputs>
        {2}
      </Inputs>
    </Execution>
    <Execution cod=""UPD"">
      <Summary>UPD Summary</Summary>
      <Table>{0}</Table>
      <Inputs>
        {1}
      </Inputs>
    </Execution>
    <Execution cod=""DEL"">
      <Summary>DEL Summary</Summary>
      <Table>{0}</Table>
      <Inputs>
        {3}
      </Inputs>
    </Execution>
  </Storable>

")]
        public string Napier_Execution_XML {
            get {
                return ((string)(this["Napier_Execution_XML"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\r\n<div class=\"form-group\">\r\n\t<label for=\"{0}\">{0}</label><br />\r\n\t<input value=\"@" +
            "Model.{0}\" type=\"text\" id=\"{0}\" name=\"{0}\"  class=\"form-control\" {1} />\r\n</div>\r" +
            "\n")]
        public string HtmlInput {
            get {
                return ((string)(this["HtmlInput"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[NapierClassMapper(\"{2}\")]\r\npublic class {0}\r\n{\r\n\t{1}\r\n}\r\n")]
        public string DTOModel {
            get {
                return ((string)(this["DTOModel"]));
            }
        }
    }
}
