//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWBrasil.ORM.CommandTemplate {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Templates : global::System.Configuration.ApplicationSettingsBase {
        
        private static Templates defaultInstance = ((Templates)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Templates())));
        
        public static Templates Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"IF EXISTS ( SELECT 1 FROM sys.objects WHERE type='P' AND name='{0}')
	DROP PROC {0}
GO


CREATE PROC dbo.{0} 
(
	{1}
	,@AbreTransacao		char(1)		= 'N'
	,@CodigoRetorno		int			=  0	output
	,@DescricaoRetorno	varchar(max)= ''	output
) AS
BEGIN

	DECLARE @TransacaoAberta char(1)
		SET @TransacaoAberta = 'N'

	BEGIN TRY

		IF @AbreTransacao = 'S'
		BEGIN
			BEGIN TRAN 
			SET @TransacaoAberta = 'S'
		END


		{2}


		SELECT 	 @CodigoRetorno		= 0
				,@DescricaoRetorno	= ''


		IF @TransacaoAberta = 'S'
		BEGIN
			COMMIT TRAN
			SET @TransacaoAberta = 'N'
		END

	END TRY
	BEGIN CATCH

		SELECT 	 @CodigoRetorno		= -9
				,@DescricaoRetorno	= 'Erro de Processamento'
				

		IF @TransacaoAberta = 'S'
		BEGIN
			ROLLBACK TRAN
			SET @TransacaoAberta = 'N'
		END

	END CATCH

END
GO
")]
        public string Procedure_Base {
            get {
                return ((string)(this["Procedure_Base"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\r\n--SAVE\r\nIF EXISTS( SELECT 1 FROM {0} WHERE {1})\r\nBEGIN\r\n\r\n\tUPDATE\r\n\t\t{0}\r\n\tSET\r" +
            "\n\t\t{2}\r\n\tWHERE\r\n\t\t{1}\r\n\r\nEND\r\nELSE\r\nBEGIN\r\n\r\n\tINSERT\r\n\t\tINTO {0}\r\n\t\t(\r\n\t\t\t{3}\r\n\t" +
            "\t)\r\n\t\tVALUES\r\n\t\t(\r\n\t\t\t{4}\r\n\t\t)\r\n\r\n\t{5}\r\n\r\nEND")]
        public string Procedure_Save {
            get {
                return ((string)(this["Procedure_Save"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\r\nSELECT \r\n\t{0}\r\nFROM\r\n\t{1}\r\nWHERE\r\n\t{2}")]
        public string Procedure_Select {
            get {
                return ((string)(this["Procedure_Select"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DELETE FROM {0} WHERE {1}")]
        public string Procedure_Delete {
            get {
                return ((string)(this["Procedure_Delete"]));
            }
        }
    }
}
