//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWBrasil.ORM.Common {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class ORM : global::System.Configuration.ApplicationSettingsBase {
        
        private static ORM defaultInstance = ((ORM)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new ORM())));
        
        public static ORM Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Desenvolvimento\\SwBrasil\\ORM\\SWBrasil.ORM\\SWBrasil.ORM.CommandTemplate\\bin\\Deb" +
            "ug")]
        public string TemplatesPath {
            get {
                return ((string)(this["TemplatesPath"]));
            }
        }
    }
}
